#! /bin/bash

# Run some task using ClojureScript

if [ $# -eq 0 ]
then
    # Default if nothing else is specified is a REPL plus listening
    # for Socket REPL
    TASK="socket"
elif [ $# -eq 1 ]
then
    TASK="$1"
else
    1>&2 echo "usage: `basename $0` arg1"
    exit 1
fi

set -x

case ${TASK} in
sock*)
    # Run REPL, with option to listen for Socket REPL connection, and
    # test paths in classpath.
    exec clj -A:cljs:cljs-test:cljs-socket ;;
test*)
    # Run 'short' tests
    exec clj -A:cljs:cljs-test:cljs-runt ;;
long*)
    # Run long/generative tests
    exec clj -A:cljs:cljs-test:cljs-runlongtests ;;
coll*)
    # Run collection-check generative tests
    exec clj -A:cljs:cljs-test:cljs-check:cljs-runcheck ;;
*)
    1>&2 echo "unknown task name: ${TASK}"
    exit 1 ;;
esac
